title: "Data Engineering On-Prem : Lakehouse logistique"
description: "Plateforme analytique on-premise sur données logistiques portuaires, douanières et de commerce international."
show_downloads: false
theme: jekyll-theme-cayman
lang: fr
